spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/boot-test?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password:
  thymeleaf:
    cache: false

